version: '3.4'

services:
  mongo:
    image: mongodb/mongodb-community-server:latest
    environment:
      - MONGO_INITDB_ROOT_USERNAME=user
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - ./mongo-data:/data/db
    ports:
      - "27017:27017"

  web:
    build:
      context: .
      dockerfile: deployment/Dockerfile
    ports:
      - "8000:8000"
    environment:
      - ENV=remote
      - MONGO_USER=user
      - MONGO_PWD=password
      - MONGO_URL=mongo:27017
    depends_on:
      - mongo
