apiVersion: apps/v1
kind: Deployment
metadata:
  name: processor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: processor
  template:
    metadata:
      labels:
        app: processor
    spec:
      containers:
        - name: backend
          image: image-processor:latest
          # This is needed to use local image for minikube
          # On real cluster, should be deleted
          imagePullPolicy: Never
          ports:
            - containerPort: 8000
          env:
            - name: ENV
              value: "remote"
            - name: MONGO_USER
              value: "<user>"
            - name: MONGO_PWD
              value: "<password>"
            - name: MONGO_URL
              value: "mongodb-service:27017"
          readinessProbe:
            httpGet:
              path: /up
              port: 8000
            periodSeconds: 30
            initialDelaySeconds: 10
            successThreshold: 2
          livenessProbe:
            httpGet:
              path: /up
              port: 8000
            periodSeconds: 120
            initialDelaySeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: processor-service
spec:
  type: NodePort
  selector:
    app: processor
  ports:
  - port: 8000
    targetPort: 8000
