version: 1
disable_existing_loggers: false
formatters:
  standard:
    format: "%(asctime)s [%(levelname)s] [%(name)s]:  %(message)s"
    "()": "uvicorn.logging.DefaultFormatter"
    use_colors: true

handlers:
  console:
    class: logging.StreamHandler
    formatter: standard
    stream: ext://sys.stdout

loggers:
  uvicorn:
    error:
      propagate: false

root:
  level: INFO
  handlers: [console]
  propagate: false
